services:
  mariadb:
    build: ./mariadb
    restart: always
    volumes:
      - ./minestore/mysql-data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./minestore/site:/var/www/minestore
      - php-socket:/run/php
    depends_on:
      - mariadb
      - nginx
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   volumes:
  #     - ./minestore/site:/var/www/minestore
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   expose:
  #     - 3000
  #   depends_on:
  #     - backend
  nginx:
    build: ./nginx
    restart: always
    env_file:
      - .env
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ./minestore/site:/var/www/minestore
      - php-socket:/run/php
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  php-socket:
